language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- yarn docs:build
branches:
  only:
  - master
install:
- yarn install
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
env:
  matrix:
    secure: DI7ZfAtuM2w7PrMQWbLc0P9tXMJ+BosK8HmLTHIKtYsuGYZjaEqqVThVddfQIOVJfkfNQTn2bxQwZybi3AXKphpyyzU/vtZHF+8EQD98rVwnZlG+aiz4PgWujgNbdhj3eJC61+y32Spi7lb0pepeBbOo9vwm2B/e/nj7cAHBSG6haw7LiHCzYgLRYWmXMVt601/KbFVMCoXzoEfUVwWtgGqxJtywV+fsxMX48Ud+uuqnILVnLOoxG8dwSFeIGVw91MrdrVLa61UW0r0Tn6Qzv+KPAhCX/OnB3/KX9JFbM60jF2mcJsUkSJVNVih8ivAtJ/SlonqieiF1Q9OG8qQTKCbHF8WVIqfLCBGPDA9QObUy3Ze7xPdLcwZ1qt7zuPQvW7fHzG89ut7Kp3Y4XZwokp89tmlw2Ob1/kjhGLSQUmbt8qWrQze81RMujZk/wDzxewdSPcOpYHG3GgVnrjc1UAF0VZn6Oi5M7SfDbUqV7PzXCyAccr4PXpJ63YeLrTdA2V4fwg+3jEjjJQ0bMKV/6NjBtvKDMxeVZ3r4eWWvfT77feK9VrXopZiZ4i4CUYd1gmqRk86CHDlA1DR+5UvOzieAQQvuCi4WPSAmLpQ0JJC676XoHAFVEQiOvny53MDtlGF3fln6fmW0Z3aUMXdVqGh4aBzrudgZVNJbePVv8B0=
